### ISSUE TITLE
Milestone 2 | Governance Actions | Motions

### ISSUE THREAD

**Issue by lmdobreva** [litentry/litentry-app#127]
> As a user, I want to be able to vote or close a motion:

### acceptance criteria 
- [x] show all the available motions
- [x] motion params should be accessible by expanding the motion
- [x] user should be able to close a motion after the voting period is passed.
- [x] user should be able to vote during the voting period
