### ISSUE TITLE
Feature: Milestone 2 | Governance Actions | Democracy 

### ISSUE THREAD

**Issue by ahoseinian** [litentry/litentry-app#136]
investigation is required to find the acceptance criteria
details to be filled

**Comment by stephanie-olp** [comment]
At least 4 tickets (ranked by order of priority : 

- [x] **Ticket 1: Vote on a Proposal (Referenda)**
As a Dot holder I’d like to vote during a referenda  

- [x] **Ticket 2: Second a Proposal**
 As a Dot holder I’d like to second a proposal 
 
- [x] **Ticket 3: Submit a Proposal**
 As a Dot holder I’d like to submit a Proposal 

- [ ] **Ticket 4: Submit a Preimage**
 As a Dot holder I’d like to submit a Preimage (=the hash of the proposal to be enacted)
