### ISSUE TITLE
Communicate more with the community.

### ISSUE THREAD

**Issue by hanwencheng** [litentry/litentry-app#830]
Once the beta version of the app is announced, we need to build a communication channel with the Dotsama community, to help:
* Get feedback from a broad range of users.
* To make sure the development fits the direction of the Dotsama ecosystem.
* Collect feedback specially from Dotsama council members
* Promote the product to be used by more teams.

### ⚠️ what do we need?

- [ ] regularly post content in https://polkadot.polkassembly.io/motion/49
- [ ] Regularly post updates in Element channel https://app.element.io/#/room/#polkadot-direction:matrix.parity.io
- [ ] To build a specific support channel. (I suggest Element, as most of the Polkadot community members use Element)

**Comment by hanwencheng** [comment]
Before we set up the community support channel, I want to keep the ticket open as a reminder.
